# Generated by Django 4.2.7 on 2023-12-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pword', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('logins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.logins')),
            ],
        ),
    ]
